//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhSanPham
    {
        public int AnhID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public Nullable<int> BienTheID { get; set; }
        public string URL { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual SanPham_BienThe SanPham_BienThe { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
