//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public long ReviewID { get; set; }
        public int SanPhamID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public string ExternalUserID { get; set; }
        public decimal Rating { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewText { get; set; }
        public bool VerifiedPurchase { get; set; }
        public string ReviewSource { get; set; }
        public System.DateTime ReviewTime { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
