//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang_ChiTiet
    {
        public int DonHangID { get; set; }
        public int BienTheID { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal GiamGia { get; set; }
        public decimal Thue { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham_BienThe SanPham_BienThe { get; set; }
    }
}
