//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.DonHang_ChiTiet = new HashSet<DonHang_ChiTiet>();
            this.VanDons = new HashSet<VanDon>();
        }
    
        public int DonHangID { get; set; }
        public int KhachHangID { get; set; }
        public string TrangThai { get; set; }
        public string KenhBan { get; set; }
        public decimal TongTienHang { get; set; }
        public decimal TongGiamGia { get; set; }
        public decimal Thue { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public decimal TongThanhToan { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang_ChiTiet> DonHang_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanDon> VanDons { get; set; }
    }
}
