//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_BienThe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham_BienThe()
        {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.DonHang_ChiTiet = new HashSet<DonHang_ChiTiet>();
            this.User_Product_Interaction = new HashSet<User_Product_Interaction>();
        }
    
        public int BienTheID { get; set; }
        public int SanPhamID { get; set; }
        public int MauID { get; set; }
        public int SizeID { get; set; }
        public string SKU { get; set; }
        public string Barcode { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSanPham> AnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang_ChiTiet> DonHang_ChiTiet { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Product_Interaction> User_Product_Interaction { get; set; }
        public virtual TonKho TonKho { get; set; }
    }
}
