//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKho
    {
        public int BienTheID { get; set; }
        public int OnHand { get; set; }
        public int Reserved { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public Nullable<int> Available { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual SanPham_BienThe SanPham_BienThe { get; set; }
    }
}
