//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Product_Interaction
    {
        public long InteractionID { get; set; }
        public int KhachHangID { get; set; }
        public int SanPhamID { get; set; }
        public Nullable<int> BienTheID { get; set; }
        public string EventType { get; set; }
        public Nullable<int> ViewTimeSec { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Channel { get; set; }
        public string Referrer { get; set; }
        public string Device { get; set; }
        public string SessionID { get; set; }
        public System.DateTime OccurredAt { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual SanPham_BienThe SanPham_BienThe { get; set; }
    }
}
