//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanDon
    {
        public int VanDonID { get; set; }
        public int DonHangID { get; set; }
        public string DVVC { get; set; }
        public string MaVanDon { get; set; }
        public string TrangThaiGiao { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
