//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Stylo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserProduct_Trainset
    {
        public int KhachHangID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public Nullable<int> view_cnt { get; set; }
        public Nullable<int> click_cnt { get; set; }
        public Nullable<int> addcart_cnt { get; set; }
        public Nullable<int> purchase_cnt { get; set; }
        public Nullable<int> avg_view_time { get; set; }
        public Nullable<System.DateTime> last_interaction_at { get; set; }
        public Nullable<int> has_received_offer { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public Nullable<int> ThuongHieuID { get; set; }
        public Nullable<decimal> AvgRating { get; set; }
        public Nullable<int> RatingCount { get; set; }
    }
}
